context:
  version: "0.1.4"

package:
  name: mdgithub
  version: ${{ version }}

source:
  path: ..

build:
  number: 3
  noarch: python
  script: pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python >=3.8
    - pip
    - hatchling
  run:
    - python >=3.8
    - pygments >=2.15.0
    - markdown >=3.4.0

tests:
  - python:
      imports:
        - mdgithub
  - script:
      - mdgithub --help

about:
  homepage: https://github.com/llango/mdgithub
  license: 0BSD
  # license_file: LICENSE
  summary: Flatten GitHub repositories into beautiful single HTML pages
  description: |
    A professional tool to flatten any GitHub repository into a single,
    beautiful HTML page with enhanced UI/UX for both humans and LLMs.
  repository: https://github.com/llango/mdgithub

extra:
  recipe-maintainers:
    - llango