[project]
name = "mdgithub"
version = "0.1.0"
description = "Flatten GitHub repositories into beautiful single HTML pages"
authors = ["llango <724261350@qq.com>"]
channels = ["https://conda.modular.com/max-nightly", "conda-forge"]
platforms = ["linux-64"]
readme = "README.md"
license = "0BSD"
homepage = "https://github.com/llango/mdgithub"
repository = "https://github.com/llango/mdgithub"

[dependencies]
python = ">=3.10"
markdown = ">=3.9,<4"
pygments = ">=2.19.2,<3"

[tasks]
# 运行主程序
flatten = "python flatten.py"

# 安装开发依赖
dev = "pixi install"

# 测试命令
test = "python -m pytest tests/"

# 代码格式化
format = "python -m black ."

# 代码检查
lint = "python -m ruff check ."

[feature.dev.dependencies]
pytest = ">=7.0"
black = ">=23.0"
ruff = ">=0.1.0"

[environments]
default = { solve-group = "default" }
dev = { features = ["dev"], solve-group = "default" }
